### PR TITLE
Url image loading

### PR DESCRIPTION
**Pull request by aleannab**
This adds in the ability to load an image via url. This functionality is currently being used in Boise State World Museum.

I also cleaned up and reordered the steps for checking for metadata depending on whether the path exists or begins with http.

### CODE REVIEW

**Comment by gordeaoux** [comment]
I think this just needs a way to bypass the metadata loading step, which looks like it could indefinitely block just trying to find the width / height of the image. Once that's in place, we can merge this in

**Comment by gordeaoux** [comment]
@aleannab functionality looks good - though is there a reason you decided to use a parameter on the function instead of the flags (like IMAGE_CACHE_F)?

**Comment by aleannab** [comment]
@gordeaoux - ah. I ended up using an additional parameter instead of adding another flag value - because it looked like those flags (e.g. IMAGE_CACHE_F), were passed on specifically to the image loading service. And I assumed that one might want different combinations of those flags plus the option to use metadata or not.

**Comment by aleannab** [comment]
Converted metadata parameter into bitmask flag. Also fixed some bugs for netsynced images.

Tested on Boise State Art Museum for images loaded via filepath, and url + no metadata.

**Pull request merged**
