### PR TITLE
Fit to limit

### PR DESCRIPTION
**Pull request by afrancois**
An attempt at fit to render. This works by first trying to find a maximum font size for the widest word vs the resize width. This is to prevent awkward line breaks in the middle of a word. Then we starting a font size 5 increment the font size until we find a size that fits in the resize_height. It works well as far as I've tested but it is not super fast. https://www.pivotaltracker.com/story/show/171890614

### CODE REVIEW

**Comment by gordeaoux** [comment]
@afrancois a couple of thoughts/questions:

- Why is the calculation done in the update loop instead of when text is measured? Is the concern that we don't want to recalculate the fit too many times while properties are being set?
- Am I reading it right that it only sizes to the widest word? 
- I assume there's no Pango APIs for it to parse out the markup or line breaks? I think there's some "layout functions". I also wonder if there's anything we could use Pango for to skip past the "while" loop for setting the font size.
- Another thing to consider might be leveraging the resize limit height negative values to limit the auto-fit to certain numbers of lines. For instance, -1 is supposed to limit the text to one line, -2 to two lines, etc. We could potentially do the same thing here where if the resize limit was "420, -1", we fit the text so it's inside of 420 pixels wide but one line of text.
- It'd be very helpful to support mShrinkToBounds for text that now fits the width but doesn't exactly match the resize limit height

**Comment by afrancois** [comment]
> @afrancois a couple of thoughts/questions:
> 
> * Why is the calculation done in the update loop instead of when text is measured? Is the concern that we don't want to recalculate the fit too many times while properties are being set?
This code was originally done **to** a Text Sprite instance and not **by** a text sprite instance. in moving it into the text-sprite I was attempting to lower the risk of changing how text currently works by leaving the measure function mostly alone. I found I didn't have appropriate knowledge to pango to make that kind of alteration. That said, I'm pretty sure it can be done.

> * Am I reading it right that it only sizes to the widest word?
Nope. Its finding the the largest font that the will make the widest word **not** wrap. Otherwise the height calculation may find a font size that causes long words with no breaks to break awkwardly in the middle.
> * I assume there's no Pango APIs for it to parse out the markup or line breaks? I think there's some "layout functions". I also wonder if there's anything we could use Pango for to skip past the "while" loop for setting the font size. 
Perhaps. When I started this, Pango wasn't part of what I was trying to do. I'll look into it more.

> * Another thing to consider might be leveraging the resize limit height negative values to limit the auto-fit to certain numbers of lines. For instance, -1 is supposed to limit the text to one line, -2 to two lines, etc. We could potentially do the same thing here where if the resize limit was "420, -1", we fit the text so it's inside of 420 pixels wide but one line of text.
We can absolutely do this. I didn't notice that logic in the text class, but I think doing this is different (simpler) math than fitting to a rectangle.

> * It'd be very helpful to support mShrinkToBounds for text that now fits the width but doesn't exactly match the resize limit height. Does this not work. Looking at the code it looks like it should, So I'll look into it.

**Comment by gordeaoux** [comment]
* RE: -1 for one text line: that's logic inside the pango layout stuff, so it makes sense you wouldn't have seen it in ds::Text
* mShrinkToBounds: I didn't check to be honest, I just read through the code and didn't see any specific handling and made an assumption :)

**Comment by gordeaoux** [comment]
Overall, this is great. Renders quickly, the controls make sense and the example is good. The only thing I think is a bit weird is the values for fit_font_maxmin. It didn't make sense to me that the maximum was first. Maybe it should be fit_font_size_range and do {min}, {max}? It's odd to me that the max is first. So something like fit_font_size_range="12, 36"

**Pull request merged**
